# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

root = "."
tmp_dir = ".air"

[build]
  cmd = "go build -gcflags=\"all=-N -l\" -o ./.air/khi-dev ./cmd/kubernetes-history-inspector/..."
  bin = "./.air/khi-dev"
  include_ext = ["go", "yaml", "json"]
  include_dir = ["cmd", "pkg"]
  exclude_dir = [
    ".air",
    "bin",
    "web",
    "scripts",
    "docs",
    "pprof",
    "pkg/server/dist",
    "pkg/testutil",
    "pkg/core/inspection/taskbasetest",
    "pkg/core/inspection/test",
    "pkg/core/inspection/formtask/test",
    "pkg/core/task/test"
  ]
  exclude_regex = ["_test\\.go$", "testdata/"]
  delay = 500
  stop_on_error = true
  send_interrupt = true
  kill_delay = "1s"

[log]
  time = true

[misc]
  clean_on_exit = true
