# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

x-build-args: &build-args
  # Version arguments
  GO_VERSION: ${GO_VERSION}
  NODE_VERSION: ${NODE_VERSION}
  KUBECTL_VERSION: ${KUBECTL_VERSION}
  
  # Hash verification arguments
  GO_SHA256: ${GO_SHA256}
  NODE_AMD64_SHA256: ${NODE_AMD64_SHA256}
  NODE_ARM64_SHA256: ${NODE_ARM64_SHA256}
  KUBECTL_SHA256: ${KUBECTL_SHA256}

services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        <<: *build-args
        UBUNTU_VERSION: "22.04"
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        USERNAME: ${USERNAME}
    network_mode: host
    volumes:
      # Project files
      - ../:/workspace:cached
      # Cache directories
      - go-cache:/home/${USERNAME}/.cache/go-build
      - go-mod-cache:/go/pkg/mod
      # Development configurations
      - ~/.ssh:/home/${USERNAME}/.ssh:cached
      - ~/.gnupg:/home/${USERNAME}/.gnupg:cached
      # Container runtime
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
    environment:
      # Go configuration
      - GOPATH=/go
      - GOMODCACHE=/go/pkg/mod
      - GOCACHE=/home/${USERNAME}/.cache/go-build
      # Node configuration
      - NODE_ENV=development
      # Path configuration
      - PATH=/usr/local/go/bin:/go/bin:/usr/local/node/bin:${PATH}
      # Build optimizations
      - DOCKER_BUILDKIT=1

    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    command: sleep infinity

volumes:
  go-cache:
  go-mod-cache: