/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { CommonModule } from '@angular/common';
import {
  AfterViewInit,
  Component,
  computed,
  DestroyRef,
  effect,
  ElementRef,
  inject,
  input,
  model,
  NgZone,
  output,
  signal,
  viewChild,
} from '@angular/core';
import { TimelineRulerRenderer as TimelineRulerCanvasRenderer } from './canvas/timeline-ruler-renderer';
import { MatIconModule } from '@angular/material/icon';
import { KHIIconRegistrationModule } from 'src/app/shared/module/icon-registration.module';
import { RenderingLoopManager } from './canvas/rendering-loop-manager';
import { TimelineRulerViewModel } from './timeline-ruler.viewmodel';
import { TimelineRulerStyle } from 'src/app/timeline/components/style-model';
import { calculateDateLabels } from './calculator/date-label-calculator';
import {
  TimeRangeDragMode,
  TimeRangeMs,
  TimeRangeOverlayStyle,
} from './interaction-model';

/**
 * Component that renders the timeline ruler, displaying time ticks and date labels.
 *
 * This component combines a Canvas-based renderer (`TimelineRulerCanvasRenderer`) for high-performance
 * tick rendering and standard Angular template bindings for date labels. It synchronizes with the
 * `RenderingLoopManager` to ensure smooth animations during scrolling and zooming.
 */
@Component({
  selector: 'khi-timeline-ruler',
  imports: [CommonModule, MatIconModule, KHIIconRegistrationModule],
  templateUrl: './timeline-ruler.component.html',
  styleUrls: ['./timeline-ruler.component.scss'],
})
export class TimelineRulerComponent implements AfterViewInit {
  protected readonly TimeRangeDragMode = TimeRangeDragMode;

  private readonly container =
    viewChild<ElementRef<HTMLDivElement>>('container');
  private readonly backgroundCanvas =
    viewChild<ElementRef<HTMLCanvasElement>>('backgroundCanvas');

  private readonly ngZone = inject(NgZone);

  private readonly destroyRef = inject(DestroyRef);

  private readonly renderingLoopManager = inject(RenderingLoopManager);

  /**
   * The timezone offset in hours to apply to the displayed time.
   * Positive values move ahead of UTC, negative values move behind.
   */
  timezoneShift = input(0);

  /**
   * The view model containing the calculated tick marks and hierarchy for the ruler.
   * This is typically generated by `RulerViewModelCalculator`.
   */
  viewModel = input.required<TimelineRulerViewModel>();

  /**
   * Configuration for the visual style of the ruler, such as colors and dimensions.
   */
  rulerStyle = input.required<TimelineRulerStyle>();

  /**
   * The timestamp (in milliseconds) corresponding to the visible left edge of the timeline.
   */
  leftEdgeTime = input<number>(0);

  /**
   * The current zoom level, expressed as pixels per millisecond.
   */
  pixelsPerMs = input<number>(1);

  /**
   * Currently active time range filter window in milliseconds, if any.
   */
  readonly activeTimeRangeMs = input<TimeRangeMs | null>(null);

  /**
   * Interactive preview time range window in milliseconds while dragging on the ruler, if any.
   */
  readonly previewTimeRangeMs = model<TimeRangeMs | null>(null);

  /**
   * Emits when a time range selection is completed by dragging on the ruler.
   */
  readonly timeRangeSelected = output<TimeRangeMs>();

  /**
   * Emits when the user requests clearing the active time range filter.
   */
  readonly timeRangeCleared = output<void>();

  /**
   * Emits when the scaling mode is changed.
   */
  scalingMode = model<boolean>();

  /**
   * Emits when the ruler is scrolled.
   */
  scrollOnRuler = output<WheelEvent>();

  private readonly activeDragMode = signal<TimeRangeDragMode | null>(null);
  private dragAnchorMs: number | null = null;
  private dragStartClientX = 0;
  private dragContainerLeft = 0;
  private removeDragListeners: (() => void) | null = null;

  private computeOverlayStyle(
    range: TimeRangeMs | null,
  ): TimeRangeOverlayStyle | null {
    if (!range) return null;
    return {
      left: (range.startMs - this.leftEdgeTime()) * this.pixelsPerMs(),
      width: Math.max(2, (range.endMs - range.startMs) * this.pixelsPerMs()),
    };
  }

  /**
   * Whether the user is currently dragging one of the edges of the active time range.
   */
  protected readonly isResizingActiveRange = computed(() => {
    const dragMode = this.activeDragMode();
    return (
      dragMode === TimeRangeDragMode.ResizeStart ||
      dragMode === TimeRangeDragMode.ResizeEnd
    );
  });

  protected readonly activeRangeStyle = computed<TimeRangeOverlayStyle | null>(
    () => this.computeOverlayStyle(this.activeTimeRangeMs()),
  );

  protected readonly previewRangeStyle = computed<TimeRangeOverlayStyle | null>(
    () => this.computeOverlayStyle(this.previewTimeRangeMs()),
  );

  /**
   * Computes the positions and text for date labels (e.g., "YYYY/MM/DD") based on the current
   * visible time range, ensuring that day boundaries are correctly labeled.
   */
  dateLabels = computed(() => {
    const viewModel = this.viewModel();
    const visibleDuration =
      viewModel.tickTimeMS * viewModel.histogramBuckets.length;
    return calculateDateLabels(
      this.leftEdgeTime(),
      visibleDuration,
      this.pixelsPerMs(),
      this.timezoneShift(),
    );
  });

  private rulerCanvasRenderer!: TimelineRulerCanvasRenderer;

  private resizeObserver: ResizeObserver | null = null;

  /**
   * Flag to indicate that the timeline needs to be redrawn.
   */
  private invalidate = signal(true);

  constructor() {
    effect(() => {
      this.viewModel();
      this.leftEdgeTime();
      this.pixelsPerMs();
      this.invalidate.set(true);
    });
    this.destroyRef.onDestroy(() => this.cleanupDragListeners());
  }
  /**
   * Initializes the canvas renderer, registers the render loop handler,
   * and sets up the resize observer to handle window or container resizing.
   */
  ngAfterViewInit(): void {
    const backgroundCanvas = this.backgroundCanvas()!.nativeElement;
    const backgroundCtx = backgroundCanvas.getContext('2d', {
      colorSpace: 'display-p3',
    });
    if (!backgroundCtx) {
      alert(
        `Failed to get canvas 2D context. Please try reload this page or restart your computer.`,
      );
      return;
    }
    this.rulerCanvasRenderer = new TimelineRulerCanvasRenderer(backgroundCtx);

    this.renderingLoopManager.registerRenderHandler(this.destroyRef, () => {
      if (this.invalidate()) {
        this.rulerCanvasRenderer.render(
          this.viewModel(),
          this.leftEdgeTime(),
          this.pixelsPerMs(),
          this.rulerStyle(),
        );
        this.invalidate.set(false);
      }
    });

    this.resizeObserver = new ResizeObserver(() => {
      this.ngZone.runOutsideAngular(() => {
        this.handleResize();
      });
    });
    this.resizeObserver.observe(this.container()!.nativeElement);
    this.destroyRef.onDestroy(() => {
      this.resizeObserver?.disconnect();
    });

    this.ngZone.runOutsideAngular(() => {
      const onWheel = (event: WheelEvent) => {
        event.preventDefault();
        event.stopPropagation();

        this.scrollOnRuler.emit(event);
      };
      this.container()!.nativeElement.addEventListener('wheel', onWheel, {
        passive: false,
      });
      this.destroyRef.onDestroy(() => {
        this.container()!.nativeElement.removeEventListener('wheel', onWheel);
      });
    });
  }

  /**
   * Handles resize events by updating the canvas dimensions to match the container.
   * The actual resize operation is deferred to the next render frame to avoid
   * flickering and to ensure it runs in the appropriate context.
   */
  private handleResize() {
    const container = this.container()!.nativeElement;
    const canvas = this.backgroundCanvas()!.nativeElement;
    const style = this.rulerStyle();
    const dpr = window.devicePixelRatio || 1;
    canvas.style.width = `${container.clientWidth}px`;
    canvas.style.height = `${style.headerHeightInPx}px`;

    // Changing actual canvas size or notifying resizes to the renderer may clear the canvas and cause the flickering effect.
    // Delay its actual resizing on the next rendering time.
    this.renderingLoopManager.registerOnceBeforeRenderHandler(() => {
      canvas.width = container.clientWidth * dpr;
      canvas.height = style.headerHeightInPx * dpr;
      this.rulerCanvasRenderer.resize(canvas.width, canvas.height, dpr);
      this.invalidate.set(true);
    });
  }

  mouseEnter() {
    this.scalingMode.set(true);
  }

  mouseLeave() {
    this.scalingMode.set(false);
  }

  private calculateTimeMsFromClientX(clientX: number): number {
    const pixelsPerMs = this.pixelsPerMs();
    if (pixelsPerMs <= 0) {
      return Math.max(0, this.leftEdgeTime());
    }
    const relativeX = clientX - this.dragContainerLeft;
    return Math.max(0, this.leftEdgeTime() + relativeX / pixelsPerMs);
  }

  private cleanupDragListeners(): void {
    if (this.removeDragListeners) {
      this.removeDragListeners();
      this.removeDragListeners = null;
    }
  }

  /**
   * Caches the ruler container's left offset for the current drag gesture.
   * Returns false when the container element is unavailable.
   */
  private cacheDragContainerLeft(): boolean {
    const containerEl = this.container()?.nativeElement;
    if (!containerEl) {
      return false;
    }
    this.dragContainerLeft = containerEl.getBoundingClientRect().left;
    return true;
  }

  private startDrag(
    event: MouseEvent,
    mode: TimeRangeDragMode,
    anchorMs: number,
  ): void {
    this.cleanupDragListeners();

    this.dragAnchorMs = anchorMs;
    this.dragStartClientX = event.clientX;
    this.activeDragMode.set(mode);

    this.ngZone.runOutsideAngular(() => {
      const onWindowMouseMove = (moveEvent: MouseEvent) => {
        this.handleDragMove(moveEvent);
      };

      const onWindowMouseUp = (upEvent: MouseEvent) => {
        this.handleDragEnd(upEvent);
      };

      const onWindowKeyDown = (keyEvent: KeyboardEvent) => {
        if (keyEvent.key === 'Escape' && this.activeDragMode() !== null) {
          keyEvent.preventDefault();
          keyEvent.stopPropagation();
          this.cancelDrag();
        }
      };

      window.addEventListener('mousemove', onWindowMouseMove);
      window.addEventListener('mouseup', onWindowMouseUp);
      window.addEventListener('keydown', onWindowKeyDown);

      this.removeDragListeners = () => {
        window.removeEventListener('mousemove', onWindowMouseMove);
        window.removeEventListener('mouseup', onWindowMouseUp);
        window.removeEventListener('keydown', onWindowKeyDown);
      };
    });
  }

  private handleDragMove(moveEvent: MouseEvent): void {
    this.ngZone.run(() => {
      if (this.activeDragMode() === null || this.dragAnchorMs === null) {
        return;
      }
      const currentMs = this.calculateTimeMsFromClientX(moveEvent.clientX);
      const range: TimeRangeMs = {
        startMs: Math.min(this.dragAnchorMs, currentMs),
        endMs: Math.max(this.dragAnchorMs, currentMs),
      };
      this.previewTimeRangeMs.set(range);
    });
  }

  private handleDragEnd(upEvent: MouseEvent): void {
    this.ngZone.run(() => {
      const anchorMs = this.dragAnchorMs;
      const wasDragging = this.activeDragMode() !== null;
      const dragDistancePx = Math.abs(upEvent.clientX - this.dragStartClientX);
      this.cleanupDragListeners();
      this.activeDragMode.set(null);
      this.dragAnchorMs = null;
      this.previewTimeRangeMs.set(null);

      if (wasDragging && anchorMs !== null && dragDistancePx >= 3) {
        const endMs = this.calculateTimeMsFromClientX(upEvent.clientX);
        const range: TimeRangeMs = {
          startMs: Math.min(anchorMs, endMs),
          endMs: Math.max(anchorMs, endMs),
        };
        if (range.endMs > range.startMs) {
          this.timeRangeSelected.emit(range);
        }
      }
    });
  }

  private cancelDrag(): void {
    this.cleanupDragListeners();
    this.ngZone.run(() => {
      this.activeDragMode.set(null);
      this.dragAnchorMs = null;
      this.previewTimeRangeMs.set(null);
    });
  }

  /**
   * Handles mousedown on the ruler container to start creating a new time range.
   */
  protected onMouseDown(event: MouseEvent): void {
    if (event.button !== 0) {
      return;
    }
    if (!this.cacheDragContainerLeft()) {
      return;
    }
    event.preventDefault();
    event.stopPropagation();
    this.startDrag(
      event,
      TimeRangeDragMode.Create,
      this.calculateTimeMsFromClientX(event.clientX),
    );
  }

  /**
   * Handles mousedown on a resize handle to start adjusting the corresponding edge of the active time range.
   * The opposite edge of the active range becomes the fixed anchor of the drag.
   */
  protected onResizeHandleMouseDown(
    event: MouseEvent,
    mode: TimeRangeDragMode,
  ): void {
    if (event.button !== 0) {
      return;
    }
    const activeRange = this.activeTimeRangeMs();
    if (!activeRange) {
      return;
    }
    if (!this.cacheDragContainerLeft()) {
      return;
    }
    event.preventDefault();
    event.stopPropagation();
    const anchorMs =
      mode === TimeRangeDragMode.ResizeStart
        ? activeRange.endMs
        : activeRange.startMs;
    this.startDrag(event, mode, anchorMs);
  }

  /**
   * Stops a mousedown on the clear button from starting a range drag on the ruler.
   */
  protected onClearButtonMouseDown(event: MouseEvent): void {
    event.preventDefault();
    event.stopPropagation();
  }

  /**
   * Handles a click on the clear button rendered on the active time range.
   */
  protected onClearButtonClick(event: MouseEvent): void {
    event.preventDefault();
    event.stopPropagation();
    this.timeRangeCleared.emit();
  }
}
