/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated by scripts/frontend-codegen; DO NOT EDIT.

/**
 * RGBA color in HDR color space.
 * All elements must be in [0, 1].
 */
export type HDRColor4 = [number, number, number, number];

// Parent relationship

/**
 * ParentRelationship type represents how the timeline relates its parent timeline.
 */
export enum ParentRelationship {
  RelationshipChild = 0,
  RelationshipResourceCondition = 1,
  RelationshipOperation = 2,
  RelationshipEndpointSlice = 3,
  RelationshipContainer = 4,
  RelationshipNodeComponent = 5,
  RelationshipOwnerReference = 6,
  RelationshipPodBinding = 7,
  RelationshipNetworkEndpointGroup = 8,
  RelationshipManagedInstanceGroup = 9,
  RelationshipControlPlaneComponent = 10,
  RelationshipSerialPort = 11,
  RelationshipAirflowTaskInstance = 12,
  RelationshipCSMAccessLog = 13,
  RelationshipPodPhase = 14,

  Unknown = -1,
}

export interface ParentRelationshipMetadataType {
  visible: boolean;
  label: string;
  hint: string;
  backgroundColor: HDRColor4;
  color: HDRColor4;
}

export const ParentRelationshipMetadata: ParentRelationshipMetadataType[] = [
  {
    visible: false,
    label: 'resource',
    hint: 'General resource lifecycle and logs',
    backgroundColor: [0.8, 0.8, 0.8, 1.0],
    color: [0.0, 0.0, 0.0, 1.0],
  },
  {
    visible: true,
    label: 'condition',
    hint: 'Resource conditions from .status.conditions',
    backgroundColor: [0.298039, 0.160784, 0.909804, 1.0],
    color: [1.0, 1.0, 1.0, 1.0],
  },
  {
    visible: true,
    label: 'operation',
    hint: 'GCP operations associated with this resource',
    backgroundColor: [0.0, 0.0, 0.0, 1.0],
    color: [1.0, 1.0, 1.0, 1.0],
  },
  {
    visible: true,
    label: 'endpoint',
    hint: 'Pod serving status from EndpointSlice',
    backgroundColor: [0.0, 0.501961, 0.0, 1.0],
    color: [1.0, 1.0, 1.0, 1.0],
  },
  {
    visible: true,
    label: 'container',
    hint: 'Container status and logs',
    backgroundColor: [0.996078, 0.607843, 0.670588, 1.0],
    color: [0.0, 0.0, 0.0, 1.0],
  },
  {
    visible: true,
    label: 'node-component',
    hint: 'Non-containerized component on the node',
    backgroundColor: [0.0, 0.466667, 0.8, 1.0],
    color: [1.0, 1.0, 1.0, 1.0],
  },
  {
    visible: true,
    label: 'owns',
    hint: 'Child resource from .metadata.ownerReferences',
    backgroundColor: [0.2, 0.866667, 0.533333, 1.0],
    color: [0.0, 0.0, 0.0, 1.0],
  },
  {
    visible: true,
    label: 'binds',
    hint: 'Pod binding subresource associated with this node',
    backgroundColor: [1.0, 0.533333, 0.333333, 1.0],
    color: [0.0, 0.0, 0.0, 1.0],
  },
  {
    visible: true,
    label: 'neg',
    hint: 'Associated NEG serving status',
    backgroundColor: [0.647059, 0.164706, 0.164706, 1.0],
    color: [1.0, 1.0, 1.0, 1.0],
  },
  {
    visible: true,
    label: 'mig',
    hint: 'MIG logs for the parent node pool',
    backgroundColor: [1.0, 0.333333, 0.333333, 1.0],
    color: [1.0, 1.0, 1.0, 1.0],
  },
  {
    visible: true,
    label: 'controlplane',
    hint: 'Control plane component of the cluster',
    backgroundColor: [1.0, 0.333333, 0.333333, 1.0],
    color: [1.0, 1.0, 1.0, 1.0],
  },
  {
    visible: true,
    label: 'serialport',
    hint: 'Serial port logs of the node',
    backgroundColor: [0.2, 0.2, 0.2, 1.0],
    color: [1.0, 1.0, 1.0, 1.0],
  },
  {
    visible: true,
    label: 'task',
    hint: 'Airflow Task Instance execution state',
    backgroundColor: [0.215686, 0.494118, 0.133333, 1.0],
    color: [1.0, 1.0, 1.0, 1.0],
  },
  {
    visible: true,
    label: 'csm',
    hint: 'CSM Access logs related to this resource',
    backgroundColor: [1.0, 0.521569, 0.0, 1.0],
    color: [1.0, 1.0, 1.0, 1.0],
  },
  {
    visible: true,
    label: 'pod',
    hint: 'Pod status on the node from .status.phase',
    backgroundColor: [1.0, 0.533333, 0.333333, 1.0],
    color: [1.0, 1.0, 1.0, 1.0],
  },
];

export function ParentRelationshipToLabel(rel: ParentRelationship): string {
  return ParentRelationshipMetadata[rel].label;
}

export function ParseParentRelationshipLabel(
  label: string,
): ParentRelationship {
  switch (label) {
    case 'resource':
      return ParentRelationship.RelationshipChild;
    case 'condition':
      return ParentRelationship.RelationshipResourceCondition;
    case 'operation':
      return ParentRelationship.RelationshipOperation;
    case 'endpoint':
      return ParentRelationship.RelationshipEndpointSlice;
    case 'container':
      return ParentRelationship.RelationshipContainer;
    case 'node-component':
      return ParentRelationship.RelationshipNodeComponent;
    case 'owns':
      return ParentRelationship.RelationshipOwnerReference;
    case 'binds':
      return ParentRelationship.RelationshipPodBinding;
    case 'neg':
      return ParentRelationship.RelationshipNetworkEndpointGroup;
    case 'mig':
      return ParentRelationship.RelationshipManagedInstanceGroup;
    case 'controlplane':
      return ParentRelationship.RelationshipControlPlaneComponent;
    case 'serialport':
      return ParentRelationship.RelationshipSerialPort;
    case 'task':
      return ParentRelationship.RelationshipAirflowTaskInstance;
    case 'csm':
      return ParentRelationship.RelationshipCSMAccessLog;
    case 'pod':
      return ParentRelationship.RelationshipPodPhase;
    default:
      return ParentRelationship.Unknown;
  }
}

export enum RevisionVerb {
  RevisionVerbUnknown = 0,
  RevisionVerbCreate = 1,
  RevisionVerbDelete = 2,
  RevisionVerbUpdate = 3,
  RevisionVerbPatch = 4,
  RevisionVerbDeleteCollection = 5,
  RevisionVerbReady = 6,
  RevisionVerbNonReady = 7,
  RevisionVerbOperationStart = 8,
  RevisionVerbOperationFinish = 9,
  RevisionVerbStatusUnknown = 10,
  RevisionVerbStatusTrue = 11,
  RevisionVerbStatusFalse = 12,
  RevisionVerbContainerWaiting = 13,
  RevisionVerbContainerReady = 14,
  RevisionVerbContainerNonReady = 15,
  RevisionVerbContainerSuccess = 16,
  RevisionVerbContainerError = 17,
  RevisionVerbComposerTaskInstanceScheduled = 18,
  RevisionVerbComposerTaskInstanceQueued = 19,
  RevisionVerbComposerTaskInstanceRunning = 20,
  RevisionVerbComposerTaskInstanceUpForRetry = 21,
  RevisionVerbComposerTaskInstanceSuccess = 22,
  RevisionVerbComposerTaskInstanceFailed = 23,
  RevisionVerbComposerTaskInstanceDeferred = 24,
  RevisionVerbComposerTaskInstanceUpForReschedule = 25,
  RevisionVerbComposerTaskInstanceRemoved = 26,
  RevisionVerbComposerTaskInstanceUpstreamFailed = 27,
  RevisionVerbComposerTaskInstanceZombie = 28,
  RevisionVerbComposerTaskInstanceStats = 29,
  RevisionVerbComposerTaskInstanceUnimplemented = 30,
  RevisionVerbTerminating = 31,
  RevisionVerbComposerTaskInstanceSkipped = 32,
}

export interface RevisionVerbMetadataType {
  label: string;
  selector: string;
  color: HDRColor4;
}

export const RevisionVerbMetadata: RevisionVerbMetadataType[] = [
  {
    label: 'Unknown',
    selector: 'unknown',
    color: [0.8, 0.2, 0.8, 1.0],
  },
  {
    label: 'Create',
    selector: 'create',
    color: [0.117647, 0.533333, 0.898039, 1.0],
  },
  {
    label: 'Delete',
    selector: 'delete',
    color: [0.960784, 0.286275, 0.270588, 1.0],
  },
  {
    label: 'Update',
    selector: 'update',
    color: [0.992157, 0.847059, 0.207843, 1.0],
  },
  {
    label: 'Patch',
    selector: 'patch',
    color: [0.992157, 0.847059, 0.207843, 1.0],
  },
  {
    label: 'DeleteCollection',
    selector: 'delete-collection',
    color: [0.960784, 0.286275, 0.270588, 1.0],
  },
  {
    label: 'Ready',
    selector: 'ready',
    color: [0.133333, 0.8, 0.133333, 1.0],
  },
  {
    label: 'NonReady',
    selector: 'non-ready',
    color: [1.0, 0.466667, 0.0, 1.0],
  },
  {
    label: 'Start',
    selector: 'operation-start',
    color: [0.133333, 0.8, 0.133333, 1.0],
  },
  {
    label: 'Finish',
    selector: 'operation-finish',
    color: [0.6, 0.6, 0.8, 1.0],
  },
  {
    label: 'Condition(Unknown)',
    selector: 'status-unknown',
    color: [0.666667, 0.4, 0.666667, 1.0],
  },
  {
    label: 'Condition(True)',
    selector: 'status-true',
    color: [0.133333, 0.8, 0.133333, 1.0],
  },
  {
    label: 'Condition(False)',
    selector: 'status-false',
    color: [1.0, 0.466667, 0.0, 1.0],
  },
  {
    label: 'Waiting',
    selector: 'container-waiting',
    color: [0.992157, 0.847059, 0.207843, 1.0],
  },
  {
    label: 'Ready',
    selector: 'container-ready',
    color: [0.133333, 0.8, 0.133333, 1.0],
  },
  {
    label: 'NonReady',
    selector: 'container-non-ready',
    color: [1.0, 0.466667, 0.0, 1.0],
  },
  {
    label: 'Success',
    selector: 'container-success',
    color: [0.0, 0.466667, 0.0, 1.0],
  },
  {
    label: 'Error',
    selector: 'container-error',
    color: [0.647059, 0.098039, 0.082353, 1.0],
  },
  {
    label: 'Scheduled',
    selector: 'composer-taskinstance-scheduled',
    color: [0.117647, 0.533333, 0.898039, 1.0],
  },
  {
    label: 'Queued',
    selector: 'composer-taskinstance-queued',
    color: [0.133333, 0.8, 0.133333, 1.0],
  },
  {
    label: 'Running',
    selector: 'composer-taskinstance-running',
    color: [0.133333, 0.8, 0.133333, 1.0],
  },
  {
    label: 'UpForRetry',
    selector: 'composer-taskinstance-upforretry',
    color: [1.0, 0.466667, 0.0, 1.0],
  },
  {
    label: 'Success',
    selector: 'composer-taskinstance-success',
    color: [0.133333, 0.8, 0.133333, 1.0],
  },
  {
    label: 'Failed',
    selector: 'composer-taskinstance-failed',
    color: [0.647059, 0.098039, 0.082353, 1.0],
  },
  {
    label: 'Deferred',
    selector: 'composer-taskinstance-deferred',
    color: [0.580392, 0.439216, 0.862745, 1.0],
  },
  {
    label: 'UpForReschedule',
    selector: 'composer-taskinstance-upforreschedule',
    color: [1.0, 0.466667, 0.0, 1.0],
  },
  {
    label: 'Removed',
    selector: 'composer-taskinstance-removed',
    color: [0.647059, 0.098039, 0.082353, 1.0],
  },
  {
    label: 'UpstreamFailed',
    selector: 'composer-taskinstance-upstreamfailed',
    color: [0.647059, 0.098039, 0.082353, 1.0],
  },
  {
    label: 'Zombie',
    selector: 'composer-taskinstance-zombie',
    color: [0.411765, 0.411765, 0.411765, 1.0],
  },
  {
    label: 'Stats',
    selector: 'composer-taskinstance-stats',
    color: [0.866667, 0.866667, 0.866667, 1.0],
  },
  {
    label: 'Unimplemented',
    selector: 'composer-taskinstance-unimplemented',
    color: [0.866667, 0.866667, 0.866667, 1.0],
  },
  {
    label: 'Terminating',
    selector: 'terminating',
    color: [1.0, 0.666667, 0.0, 1.0],
  },
  {
    label: 'Skipped',
    selector: 'composer-taskinstance-skipped',
    color: [0.901961, 0.0, 0.462745, 1.0],
  },
];

// log types
export enum LogType {
  LogTypeUnknown = 0,
  LogTypeEvent = 1,
  LogTypeAudit = 2,
  LogTypeContainer = 3,
  LogTypeNode = 4,
  LogTypeGkeAudit = 5,
  LogTypeComputeApi = 6,
  LogTypeMulticloudAPI = 7,
  LogTypeOnPremAPI = 8,
  LogTypeNetworkAPI = 9,
  LogTypeAutoscaler = 10,
  LogTypeComposerEnvironment = 11,
  LogTypeControlPlaneComponent = 12,
  LogTypeSerialPort = 13,
  LogTypeCSMAccessLog = 14,
}

export interface LogTypeMetadataType {
  label: string;
  color: HDRColor4;
}

export const LogTypeMetadata: LogTypeMetadataType[] = [
  {
    label: 'unknown',
    color: [0.0, 0.0, 0.0, 1.0],
  },
  {
    label: 'k8s_event',
    color: [0.247059, 0.709804, 0.286275, 1.0],
  },
  {
    label: 'k8s_audit',
    color: [0.0, 0.0, 0.0, 1.0],
  },
  {
    label: 'k8s_container',
    color: [0.996078, 0.607843, 0.670588, 1.0],
  },
  {
    label: 'k8s_node',
    color: [0.0, 0.466667, 0.8, 1.0],
  },
  {
    label: 'gke_audit',
    color: [0.666667, 0.0, 1.0, 1.0],
  },
  {
    label: 'compute_api',
    color: [1.0, 0.8, 0.2, 1.0],
  },
  {
    label: 'multicloud_api',
    color: [0.666667, 0.0, 1.0, 1.0],
  },
  {
    label: 'onprem_api',
    color: [0.666667, 0.0, 1.0, 1.0],
  },
  {
    label: 'network_api',
    color: [0.2, 0.8, 1.0, 1.0],
  },
  {
    label: 'autoscaler',
    color: [1.0, 0.333333, 0.333333, 1.0],
  },
  {
    label: 'composer_environment',
    color: [0.533333, 0.666667, 0.333333, 1.0],
  },
  {
    label: 'control_plane_component',
    color: [1.0, 0.2, 0.2, 1.0],
  },
  {
    label: 'serial_port',
    color: [0.2, 0.2, 0.2, 1.0],
  },
  {
    label: 'csm_access_log',
    color: [1.0, 0.521569, 0.0, 1.0],
  },
];

export const logTypes = [
  'unknown',
  'k8s_event',
  'k8s_audit',
  'k8s_container',
  'k8s_node',
  'gke_audit',
  'compute_api',
  'multicloud_api',
  'onprem_api',
  'network_api',
  'autoscaler',
  'composer_environment',
  'control_plane_component',
  'serial_port',
  'csm_access_log',
];

// Deprecated. Use LogTypeMetadata instead.
export const logTypeColors: { [logType: string]: HDRColor4 } = {
  unknown: [0.0, 0.0, 0.0, 1.0],
  k8s_event: [0.247059, 0.709804, 0.286275, 1.0],
  k8s_audit: [0.0, 0.0, 0.0, 1.0],
  k8s_container: [0.996078, 0.607843, 0.670588, 1.0],
  k8s_node: [0.0, 0.466667, 0.8, 1.0],
  gke_audit: [0.666667, 0.0, 1.0, 1.0],
  compute_api: [1.0, 0.8, 0.2, 1.0],
  multicloud_api: [0.666667, 0.0, 1.0, 1.0],
  onprem_api: [0.666667, 0.0, 1.0, 1.0],
  network_api: [0.2, 0.8, 1.0, 1.0],
  autoscaler: [1.0, 0.333333, 0.333333, 1.0],
  composer_environment: [0.533333, 0.666667, 0.333333, 1.0],
  control_plane_component: [1.0, 0.2, 0.2, 1.0],
  serial_port: [0.2, 0.2, 0.2, 1.0],
  csm_access_log: [1.0, 0.521569, 0.0, 1.0],
};

export enum RevisionState {
  RevisionStateInferred = 0,
  RevisionStateExisting = 1,
  RevisionStateDeleted = 2,
  RevisionStateConditionTrue = 3,
  RevisionStateConditionFalse = 4,
  RevisionStateConditionUnknown = 5,
  RevisionStateOperationStarted = 6,
  RevisionStateOperationFinished = 7,
  RevisionStateContainerWaiting = 8,
  RevisionStateContainerRunningNonReady = 9,
  RevisionStateContainerRunningReady = 10,
  RevisionStateContainerTerminatedWithSuccess = 11,
  RevisionStateContainerTerminatedWithError = 12,
  RevisionStateComposerTiScheduled = 13,
  RevisionStateComposerTiQueued = 14,
  RevisionStateComposerTiRunning = 15,
  RevisionStateComposerTiDeferred = 16,
  RevisionStateComposerTiSuccess = 17,
  RevisionStateComposerTiFailed = 18,
  RevisionStateComposerTiUpForRetry = 19,
  RevisionStateComposerTiRestarting = 20,
  RevisionStateComposerTiRemoved = 21,
  RevisionStateComposerTiUpstreamFailed = 22,
  RevisionStateComposerTiZombie = 23,
  RevisionStateComposerTiUpForReschedule = 24,
  RevisionStateDeleting = 25,
  RevisionStateEndpointReady = 26,
  RevisionStateEndpointTerminating = 27,
  RevisionStateEndpointUnready = 28,
  RevisionStateProvisioning = 29,
  RevisionAutoscalerNoError = 30,
  RevisionAutoscalerHasErrors = 31,
  RevisionStateConditionNotGiven = 32,
  RevisionStateConditionNoAvailableInfo = 33,
  RevisionStatePodPhasePending = 34,
  RevisionStatePodPhaseScheduled = 35,
  RevisionStatePodPhaseRunning = 36,
  RevisionStatePodPhaseSucceeded = 37,
  RevisionStatePodPhaseFailed = 38,
  RevisionStatePodPhaseUnknown = 39,
  RevisionStateContainerStatusNotAvailable = 40,
  RevisionStateContainerStarted = 41,
  RevisionStateComposerTiSkipped = 42,
}

export interface RevisionStateMetadataType {
  cssSelector: string;
  label: string;
  icon: string;
  style: RevisionStateStyle;
  color: HDRColor4;
}

export enum RevisionStateStyle {
  Normal = 0,
  Deleted = 1,
  PartialInfo = 2,
}

export const RevisionStateMetadata: RevisionStateMetadataType[] = [
  {
    cssSelector: 'inferred',
    label: 'Resource may be existing',
    icon: 'unknown_document',
    style: 2,
    color: [0.6, 0.6, 0.133333, 1.0],
  },
  {
    cssSelector: 'existing',
    label: 'Resource is existing',
    icon: 'deployed_code',
    style: 0,
    color: [0.0, 0.0, 1.0, 1.0],
  },
  {
    cssSelector: 'deleted',
    label: 'Resource is deleted',
    icon: 'delete_forever',
    style: 1,
    color: [0.8, 0.0, 0.0, 1.0],
  },
  {
    cssSelector: 'condition_true',
    label: "State is 'True'",
    icon: 'lightbulb',
    style: 0,
    color: [0.0, 0.266667, 0.0, 1.0],
  },
  {
    cssSelector: 'condition_false',
    label: "State is 'False'",
    icon: 'light_off',
    style: 0,
    color: [0.933333, 0.266667, 0.0, 1.0],
  },
  {
    cssSelector: 'condition_unknown',
    label: "State is 'Unknown'",
    icon: 'siren_question',
    style: 0,
    color: [0.4, 0.2, 0.4, 1.0],
  },
  {
    cssSelector: 'operation_started',
    label: 'Processing operation',
    icon: 'change_circle',
    style: 0,
    color: [0.0, 0.266667, 0.0, 1.0],
  },
  {
    cssSelector: 'operation_finished',
    label: 'Operation is finished',
    icon: 'check_circle',
    style: 1,
    color: [0.2, 0.2, 0.2, 1.0],
  },
  {
    cssSelector: 'container_waiting',
    label: 'Waiting for starting container',
    icon: 'deployed_code_history',
    style: 1,
    color: [0.266667, 0.266667, 1.0, 1.0],
  },
  {
    cssSelector: 'container_running_non_ready',
    label: 'Container is not ready',
    icon: 'heart_broken',
    style: 0,
    color: [0.933333, 0.266667, 0.0, 1.0],
  },
  {
    cssSelector: 'container_running_ready',
    label: 'Container is ready',
    icon: 'heart_check',
    style: 0,
    color: [0.0, 0.466667, 0.0, 1.0],
  },
  {
    cssSelector: 'container_terminated_success',
    label: 'Container exited with healthy exit code',
    icon: 'check_circle',
    style: 1,
    color: [0.066667, 0.2, 0.2, 1.0],
  },
  {
    cssSelector: 'container_terminated_error',
    label: 'Container exited with erroneous exit code',
    icon: 'error',
    style: 1,
    color: [0.333333, 0.066667, 0.066667, 1.0],
  },
  {
    cssSelector: 'composer_ti_scheduled',
    label: 'Task instance is scheduled',
    icon: 'schedule',
    style: 0,
    color: [0.819608, 0.705882, 0.54902, 1.0],
  },
  {
    cssSelector: 'composer_ti_queued',
    label: 'Task instance is queued',
    icon: 'transition_push',
    style: 0,
    color: [0.501961, 0.501961, 0.501961, 1.0],
  },
  {
    cssSelector: 'composer_ti_running',
    label: 'Task instance is running',
    icon: 'directions_run',
    style: 0,
    color: [0.0, 1.0, 0.003922, 1.0],
  },
  {
    cssSelector: 'composer_ti_deferred',
    label: 'Task instance is deferred',
    icon: 'pause',
    style: 0,
    color: [0.580392, 0.439216, 0.862745, 1.0],
  },
  {
    cssSelector: 'composer_ti_success',
    label: 'Task instance completed with success state',
    icon: 'check',
    style: 0,
    color: [0.0, 0.501961, 0.003922, 1.0],
  },
  {
    cssSelector: 'composer_ti_failed',
    label: 'Task instance completed with erroneous state',
    icon: 'exclamation',
    style: 0,
    color: [0.996078, 0.0, 0.0, 1.0],
  },
  {
    cssSelector: 'composer_ti_up_for_retry',
    label: 'Task instance is waiting for next retry',
    icon: 'camping',
    style: 0,
    color: [0.996078, 0.843137, 0.0, 1.0],
  },
  {
    cssSelector: 'composer_ti_restarting',
    label: 'Task instance is restarting',
    icon: 'restart_alt',
    style: 0,
    color: [0.933333, 0.509804, 0.937255, 1.0],
  },
  {
    cssSelector: 'composer_ti_removed',
    label: 'Task instance is removed',
    icon: 'waving_hand',
    style: 0,
    color: [0.827451, 0.827451, 0.827451, 1.0],
  },
  {
    cssSelector: 'composer_ti_upstream_failed',
    label: 'Upstream task has failed',
    icon: 'falling',
    style: 0,
    color: [1.0, 0.631373, 0.105882, 1.0],
  },
  {
    cssSelector: 'composer_ti_zombie',
    label: 'Task instance is a zombie',
    icon: 'skull',
    style: 0,
    color: [0.294118, 0.0, 0.509804, 1.0],
  },
  {
    cssSelector: 'composer_ti_up_for_reschedule',
    label: 'Task instance is waiting to be rescheduled',
    icon: 'history',
    style: 0,
    color: [0.501961, 0.501961, 0.501961, 1.0],
  },
  {
    cssSelector: 'deleting',
    label: 'Resource is under deleting with graceful period',
    icon: 'auto_delete',
    style: 0,
    color: [0.8, 0.333333, 0.0, 1.0],
  },
  {
    cssSelector: 'ready',
    label: 'Endpoint is ready',
    icon: 'heart_check',
    style: 0,
    color: [0.0, 0.266667, 0.0, 1.0],
  },
  {
    cssSelector: 'terminating',
    label: 'Endpoint is being terminated',
    icon: 'auto_delete',
    style: 0,
    color: [0.807843, 0.654902, 0.0, 1.0],
  },
  {
    cssSelector: 'unready',
    label: 'Endpoint is not ready',
    icon: 'heart_broken',
    style: 0,
    color: [0.933333, 0.266667, 0.0, 1.0],
  },
  {
    cssSelector: 'provisioning',
    label: 'Resource is being provisioned',
    icon: 'deployed_code_history',
    style: 0,
    color: [0.4, 0.4, 1.0, 1.0],
  },
  {
    cssSelector: 'autoscaler_no_error',
    label: 'Autoscaler has no error',
    icon: 'heart_check',
    style: 0,
    color: [0.0, 0.266667, 0.0, 1.0],
  },
  {
    cssSelector: 'autoscaler_has_errors',
    label: 'Autoscaler has errors',
    icon: 'heart_broken',
    style: 0,
    color: [0.933333, 0.266667, 0.0, 1.0],
  },
  {
    cssSelector: 'condition_not_given',
    label: 'Condition is not defined at this moment',
    icon: 'select',
    style: 1,
    color: [0.4, 0.4, 0.4, 1.0],
  },
  {
    cssSelector: 'condition_no_available_info',
    label: 'No enough information to show condition',
    icon: 'unknown_document',
    style: 0,
    color: [0.6, 0.466667, 0.0, 1.0],
  },
  {
    cssSelector: 'pod_phase_pending',
    label: 'Pod is pending',
    icon: 'hourglass_empty',
    style: 0,
    color: [0.4, 0.4, 0.4, 1.0],
  },
  {
    cssSelector: 'pod_phase_scheduled',
    label: 'Pod is scheduled',
    icon: 'schedule',
    style: 0,
    color: [0.266667, 0.266667, 1.0, 1.0],
  },
  {
    cssSelector: 'pod_phase_running',
    label: 'Pod is running',
    icon: 'motion_play',
    style: 0,
    color: [0.0, 0.266667, 0.0, 1.0],
  },
  {
    cssSelector: 'pod_phase_succeeded',
    label: 'Pod is succeeded',
    icon: 'check_circle',
    style: 1,
    color: [0.066667, 0.2, 0.2, 1.0],
  },
  {
    cssSelector: 'pod_phase_failed',
    label: 'Pod is failed',
    icon: 'error',
    style: 1,
    color: [0.2, 0.066667, 0.066667, 1.0],
  },
  {
    cssSelector: 'pod_phase_unknown',
    label: 'Pod status is not available from current log range',
    icon: 'unknown_document',
    style: 2,
    color: [0.6, 0.466667, 0.0, 1.0],
  },
  {
    cssSelector: 'container_status_not_available',
    label: 'Container status is not available',
    icon: 'unknown_document',
    style: 2,
    color: [0.4, 0.4, 0.4, 1.0],
  },
  {
    cssSelector: 'container_started',
    label: 'Container is started but readiness info is not available',
    icon: 'siren_question',
    style: 2,
    color: [0.6, 0.466667, 0.0, 1.0],
  },
  {
    cssSelector: 'composer_ti_skipped',
    label: 'Task instance is skipped',
    icon: 'step_over',
    style: 0,
    color: [0.901961, 0.0, 0.462745, 1.0],
  },
];

export const revisionStates = [
  'inferred',
  'existing',
  'deleted',
  'condition_true',
  'condition_false',
  'condition_unknown',
  'operation_started',
  'operation_finished',
  'container_waiting',
  'container_running_non_ready',
  'container_running_ready',
  'container_terminated_success',
  'container_terminated_error',
  'composer_ti_scheduled',
  'composer_ti_queued',
  'composer_ti_running',
  'composer_ti_deferred',
  'composer_ti_success',
  'composer_ti_failed',
  'composer_ti_up_for_retry',
  'composer_ti_restarting',
  'composer_ti_removed',
  'composer_ti_upstream_failed',
  'composer_ti_zombie',
  'composer_ti_up_for_reschedule',
  'deleting',
  'ready',
  'terminating',
  'unready',
  'provisioning',
  'autoscaler_no_error',
  'autoscaler_has_errors',
  'condition_not_given',
  'condition_no_available_info',
  'pod_phase_pending',
  'pod_phase_scheduled',
  'pod_phase_running',
  'pod_phase_succeeded',
  'pod_phase_failed',
  'pod_phase_unknown',
  'container_status_not_available',
  'container_started',
  'composer_ti_skipped',
];

// deprecated: use RevisionStateMetadata instead
export const revisionStatecolors: { [state: string]: HDRColor4 } = {
  inferred: [0.6, 0.6, 0.133333, 1.0],
  existing: [0.0, 0.0, 1.0, 1.0],
  deleted: [0.8, 0.0, 0.0, 1.0],
  condition_true: [0.0, 0.266667, 0.0, 1.0],
  condition_false: [0.933333, 0.266667, 0.0, 1.0],
  condition_unknown: [0.4, 0.2, 0.4, 1.0],
  operation_started: [0.0, 0.266667, 0.0, 1.0],
  operation_finished: [0.2, 0.2, 0.2, 1.0],
  container_waiting: [0.266667, 0.266667, 1.0, 1.0],
  container_running_non_ready: [0.933333, 0.266667, 0.0, 1.0],
  container_running_ready: [0.0, 0.466667, 0.0, 1.0],
  container_terminated_success: [0.066667, 0.2, 0.2, 1.0],
  container_terminated_error: [0.333333, 0.066667, 0.066667, 1.0],
  composer_ti_scheduled: [0.819608, 0.705882, 0.54902, 1.0],
  composer_ti_queued: [0.501961, 0.501961, 0.501961, 1.0],
  composer_ti_running: [0.0, 1.0, 0.003922, 1.0],
  composer_ti_deferred: [0.580392, 0.439216, 0.862745, 1.0],
  composer_ti_success: [0.0, 0.501961, 0.003922, 1.0],
  composer_ti_failed: [0.996078, 0.0, 0.0, 1.0],
  composer_ti_up_for_retry: [0.996078, 0.843137, 0.0, 1.0],
  composer_ti_restarting: [0.933333, 0.509804, 0.937255, 1.0],
  composer_ti_removed: [0.827451, 0.827451, 0.827451, 1.0],
  composer_ti_upstream_failed: [1.0, 0.631373, 0.105882, 1.0],
  composer_ti_zombie: [0.294118, 0.0, 0.509804, 1.0],
  composer_ti_up_for_reschedule: [0.501961, 0.501961, 0.501961, 1.0],
  deleting: [0.8, 0.333333, 0.0, 1.0],
  ready: [0.0, 0.266667, 0.0, 1.0],
  terminating: [0.807843, 0.654902, 0.0, 1.0],
  unready: [0.933333, 0.266667, 0.0, 1.0],
  provisioning: [0.4, 0.4, 1.0, 1.0],
  autoscaler_no_error: [0.0, 0.266667, 0.0, 1.0],
  autoscaler_has_errors: [0.933333, 0.266667, 0.0, 1.0],
  condition_not_given: [0.4, 0.4, 0.4, 1.0],
  condition_no_available_info: [0.6, 0.466667, 0.0, 1.0],
  pod_phase_pending: [0.4, 0.4, 0.4, 1.0],
  pod_phase_scheduled: [0.266667, 0.266667, 1.0, 1.0],
  pod_phase_running: [0.0, 0.266667, 0.0, 1.0],
  pod_phase_succeeded: [0.066667, 0.2, 0.2, 1.0],
  pod_phase_failed: [0.2, 0.066667, 0.066667, 1.0],
  pod_phase_unknown: [0.6, 0.466667, 0.0, 1.0],
  container_status_not_available: [0.4, 0.4, 0.4, 1.0],
  container_started: [0.6, 0.466667, 0.0, 1.0],
  composer_ti_skipped: [0.901961, 0.0, 0.462745, 1.0],
};

export const revisionStateToIndex: { [state: string]: number } = {};
for (let i = 0; i < revisionStates.length; i++) {
  revisionStateToIndex[revisionStates[i]] = i;
}

// severities

/**
 * Severity represents severity of a log.
 */
export enum Severity {
  SeverityUnknown = 0,
  SeverityInfo = 1,
  SeverityWarning = 2,
  SeverityError = 3,
  SeverityFatal = 4,
}

export interface SeverityMetadataType {
  label: string;
  color: HDRColor4;
  borderColor: HDRColor4;
}

export const SeverityMetadata: SeverityMetadataType[] = [
  {
    label: 'UNKNOWN',
    color: [0.0, 0.0, 0.0, 1.0],
    borderColor: [0.666667, 0.666667, 0.666667, 1.0],
  },
  {
    label: 'INFO',
    color: [0.0, 0.0, 1.0, 1.0],
    borderColor: [0.117647, 0.533333, 0.898039, 1.0],
  },
  {
    label: 'WARNING',
    color: [1.0, 0.666667, 0.266667, 1.0],
    borderColor: [0.992157, 0.847059, 0.207843, 1.0],
  },
  {
    label: 'ERROR',
    color: [1.0, 0.223529, 0.207843, 1.0],
    borderColor: [1.0, 0.533333, 0.533333, 1.0],
  },
  {
    label: 'FATAL',
    color: [0.666667, 0.4, 0.666667, 1.0],
    borderColor: [1.0, 0.6, 1.0, 1.0],
  },
];

export const severities = ['UNKNOWN', 'INFO', 'WARNING', 'ERROR', 'FATAL'];

// Deprecated. Use SeverityMetadata instead.
export const severityColors: { [state: string]: HDRColor4 } = {
  UNKNOWN: [0.0, 0.0, 0.0, 1.0],
  INFO: [0.0, 0.0, 1.0, 1.0],
  WARNING: [1.0, 0.666667, 0.266667, 1.0],
  ERROR: [1.0, 0.223529, 0.207843, 1.0],
  FATAL: [0.666667, 0.4, 0.666667, 1.0],
};

// Deprecated. Use SeverityMetadata instead.
export const severityBorderColors: { [state: string]: HDRColor4 } = {
  UNKNOWN: [0.666667, 0.666667, 0.666667, 1.0],
  INFO: [0.117647, 0.533333, 0.898039, 1.0],
  WARNING: [0.992157, 0.847059, 0.207843, 1.0],
  ERROR: [1.0, 0.533333, 0.533333, 1.0],
  FATAL: [1.0, 0.6, 1.0, 1.0],
};

export const severityToIndex: { [state: string]: number } = {};
for (let i = 0; i < severities.length; i++) {
  severityToIndex[severities[i]] = i;
}
